name: builds
on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read  # This is required for actions/checkout

jobs:
  # DockerHub builds
  keydb-dockerhub:
    uses: ./.github/workflows/docker-build-dockerhub.yml
    with:
      image_name: rudderstack/rudder-keydb
      dockerfile: Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  keydb-scaler-dockerhub:
    uses: ./.github/workflows/docker-build-dockerhub.yml
    with:
      image_name: rudderstack/rudder-keydb-scaler
      dockerfile: Dockerfile-scaler
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # ECR builds
  keydb-ecr:
    uses: ./.github/workflows/docker-build-ecr.yml
    with:
      image_name: rudderstack/rudder-keydb
      dockerfile: Dockerfile
      aws_ecr_iam_role_arn: ${{ vars.AWS_ECR_IAM_ROLE_ARN }}
      aws_ecr_region: ${{ vars.AWS_ECR_REGION }}

  keydb-scaler-ecr:
    uses: ./.github/workflows/docker-build-ecr.yml
    with:
      image_name: rudderstack/rudder-keydb-scaler
      dockerfile: Dockerfile-scaler
      aws_ecr_iam_role_arn: ${{ vars.AWS_ECR_IAM_ROLE_ARN }}
      aws_ecr_region: ${{ vars.AWS_ECR_REGION }}
